repos:
  - repo: local
    hooks:
      - id: lint
        name: Run Linter
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: Run Type Checker
        entry: make mypy
        language: system
        types: [ python ]
        pass_filenames: false
