site_name: "d9d"
site_url: "https://d9d-project.github.io/d9d/"
repo_url: "https://github.com/d9d-project/d9d"

theme:
  name: "shadcn"
  icon: "https://avatars.githubusercontent.com/u/248787421"
  show_title: true
  pygments_style:
    light: a11y-light
    dark: a11y-dark
  show_datetime: true


markdown_extensions:
  - codehilite:
      linennums: true
  - pymdownx.arithmatex:
      generic: true
  - admonition


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_options:
            returns_multiple_items: false
          docstring_style: google
          show_source: false

extra_css:
  - style/style.css